[package]
name = "parametric_equations"
version = "0.4.0"
authors = ["Ryan Christian <rchristian@rschristian.dev>"]
edition = "2018"

[dependencies]
cgmath = "0.18"
glium = "0.36.0"
glium_text = { git = "https://github.com/rschristian/glium_text" }
rand = "0.9.0"
